In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data= pd.read_csv('/content/sample_data/california_housing_train.csv')

In [3]:
data_test=pd.read_csv('/content/sample_data/california_housing_test.csv')

In [47]:
data

player    salary     AtBat      Hits     HmRun      Runs  \
0          -Alan Ashby -0.135055 -0.601753 -0.594542 -0.527545 -1.203816   
1         -Alvin Davis -0.123972  0.511566  0.491323  0.728577  0.440675   
2        -Andre Dawson -0.079637  0.626971  0.735088  0.956963  0.401520   
3    -Andres Galarraga -0.985164 -0.561022 -0.461579 -0.184967 -0.616498   
4     -Alfredo Griffin  0.474541  1.292248  1.355583 -0.870124  0.753911   
..                 ...       ...       ...       ...       ...       ...   
258      -Willie McGee  0.363705  0.633760  0.424841 -0.527545  0.401520   
259   -Willie Randolph  0.751630  0.599817  0.624286 -0.755931  0.832220   
260    -Wayne Tolleson -0.334559  0.484412  0.402681 -0.984317  0.244902   
261     -Willie Upshaw  0.940050  1.149689  0.801570 -0.299159  1.184611   
262     -Willie Wilson  1.028718  1.543424  1.377743 -0.299159  0.871375   

          RBI     Walks     Years    CAtBat  ...    CHmRun     CRuns  \
0   -0.521069 -0.097342  1.395233  0.346131  ... -0.002914 -0.121439   
1    0.792549  1.606310 -0.899485 -0.452004  ... -0.075909 -0.414315   
2    1.024364 -0.189431  0.769401  1.299081  ...  1.894952  1.409364   
3   -0.366526 -0.511743 -1.108096 -0.989050  ... -0.696365 -0.945718   
4   -0.018804 -0.281520  0.769401  0.765534  ... -0.611205  0.422041   
..        ...       ...       ...       ...  ...       ...       ...   
258 -0.134711 -0.189431 -0.482264  0.019880  ... -0.453049  0.053682   
259 -0.057440  2.435113  0.978012  1.247913  ... -0.367888  1.617699   
260 -0.327890  0.501239 -0.273653 -0.418766  ... -0.757194 -0.435450   
261  0.328919  1.698399  0.143569  0.236360  ...  0.337728  0.328442   
262 -0.289255 -0.465699  0.769401  0.984201  ... -0.477381  1.249340   

         CRBI    CWalks   LeagueN  DivisionW   PutOuts   Assists    Errors  \
0    0.258473  0.434506  1.056743   0.979299  1.219174 -0.522196  0.212946   
1   -0.199211  0.010353 -0.942706   0.979299  2.105095 -0.253380  0.818404   
2    1.569674  0.354977  1.056743  -1.017256 -0.324044 -0.742763 -0.846605   
3   -0.879551 -0.860675  1.056743  -1.017256  1.837176 -0.542874 -0.695240   
4    0.017261 -0.250955 -0.942706   0.979299 -0.031118  2.083253  2.483412   
..        ...       ...       ...        ...       ...       ...       ...   
258 -0.060050 -0.463031  1.056743  -1.017256  0.122489 -0.756548 -0.846605   
259  0.372894  2.328045 -0.942706  -1.017256  0.079622  1.807544  1.726590   
260 -0.734205 -0.432735 -0.942706   0.979299 -0.906323 -0.039705 -0.241147   
261  0.277028  0.271662 -0.942706  -1.017256  3.655458  0.084364  0.515675   
262  0.082203 -0.042666 -0.942706   0.979299  0.418987 -0.791012 -0.846605   

     NewLeagueN  
0      1.073007  
1     -0.928417  
2      1.073007  
3      1.073007  
4     -0.928417  
..          ...  
258    1.073007  
259   -0.928417  
260   -0.928417  
261   -0.928417  
262   -0.928417  

[263 rows x 21 columns]

In [48]:
data.hist()

array([[<Axes: title={'center': 'salary'}>,
        <Axes: title={'center': 'AtBat'}>,
        <Axes: title={'center': 'Hits'}>,
        <Axes: title={'center': 'HmRun'}>],
       [<Axes: title={'center': 'Runs'}>,
        <Axes: title={'center': 'RBI'}>,
        <Axes: title={'center': 'Walks'}>,
        <Axes: title={'center': 'Years'}>],
       [<Axes: title={'center': 'CAtBat'}>,
        <Axes: title={'center': 'CHits'}>,
        <Axes: title={'center': 'CHmRun'}>,
        <Axes: title={'center': 'CRuns'}>],
       [<Axes: title={'center': 'CRBI'}>,
        <Axes: title={'center': 'CWalks'}>,
        <Axes: title={'center': 'LeagueN'}>,
        <Axes: title={'center': 'DivisionW'}>],
       [<Axes: title={'center': 'PutOuts'}>,
        <Axes: title={'center': 'Assists'}>,
        <Axes: title={'center': 'Errors'}>,
        <Axes: title={'center': 'NewLeagueN'}>]], dtype=object)

In [6]:
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [7]:
data.corr()

longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.925208           -0.114250     0.047010   
latitude            -0.925208  1.000000            0.016454    -0.038773   
housing_median_age  -0.114250  0.016454            1.000000    -0.360984   
total_rooms          0.047010 -0.038773           -0.360984     1.000000   
total_bedrooms       0.071802 -0.069373           -0.320434     0.928403   
population           0.101674 -0.111261           -0.295890     0.860170   
households           0.059628 -0.074902           -0.302754     0.919018   
median_income       -0.015485 -0.080303           -0.115932     0.195383   
median_house_value  -0.044982 -0.144917            0.106758     0.130991   

                    total_bedrooms  population  households  median_income  \
longitude                 0.071802    0.101674    0.059628      -0.015485   
latitude                 -0.069373   -0.111261   -0.074902      -0.080303   
housing_median_age       -0.320434   -0.295890   -0.302754      -0.115932   
total_rooms               0.928403    0.860170    0.919018       0.195383   
total_bedrooms            1.000000    0.881169    0.980920      -0.013495   
population                0.881169    1.000000    0.909247      -0.000638   
households                0.980920    0.909247    1.000000       0.007644   
median_income            -0.013495   -0.000638    0.007644       1.000000   
median_house_value        0.045783   -0.027850    0.061031       0.691871   

                    median_house_value  
longitude                    -0.044982  
latitude                     -0.144917  
housing_median_age            0.106758  
total_rooms                   0.130991  
total_bedrooms                0.045783  
population                   -0.027850  
households                    0.061031  
median_income                 0.691871  
median_house_value            1.000000

In [8]:
sns.catplot(x='longitude',y='latitude', hue='median_house_value', data=data)

In [9]:
data_test

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [10]:
X_train=data.drop(columns=['median_house_value'])

In [11]:
X_train

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
16995       907.0       369.0         2.3571  
16996      1194.0       465.0         2.5179  
16997      1244.0       456.0         3.0313  
16998      1298.0       478.0         1.9797  
16999       806.0       270.0         3.0147  

[17000 rows x 8 columns]

In [12]:
y_train=data['median_house_value']

In [13]:
y_train

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [14]:
from sklearn.linear_model import LinearRegression


In [15]:
reg =LinearRegression()

In [16]:
reg.fit(X_train,y_train)

LinearRegression()

In [17]:
reg.score(X_train,y_train)

0.6413378529502687

In [18]:
reg.coef_

array([-4.31396373e+04, -4.29256731e+04,  1.15069493e+03, -8.37825121e+00,
        1.17648543e+02, -3.84887721e+01,  4.54360026e+01,  4.05070684e+04])

In [19]:
reg.intercept_

-3620600.8929739078

In [20]:
reg.predict([[-144.81, 37.19, 55.0, 8612.0, 1583.0, 1115.0, 482.0, 1.8936]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1263105.91828829])

In [21]:
reg.score(X_train,y_train)

0.6413378529502687

In [22]:
X_test =data_test.drop(columns=['median_house_value'])

In [23]:
X_test

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  
0         1537.0       606.0         6.6085  
1          809.0       277.0         3.5990  
2         1484.0       495.0         5.7934  
3           49.0        11.0         6.1359  
4          850.0       237.0         2.9375  
...          ...         ...            ...  
2995      1258.0       607.0         1.1790  
2996      3496.0      1036.0         3.3906  
2997       693.0       220.0         2.2895  
2998        46.0        14.0         3.2708  
2999       753.0       260.0         8.5608  

[3000 rows x 8 columns]

In [24]:
y_test=data_test['median_house_value']

In [25]:
y_test

0       344700.0
1       176500.0
2       270500.0
3       330000.0
4        81700.0
          ...   
2995    225000.0
2996    237200.0
2997     62000.0
2998    162500.0
2999    500001.0
Name: median_house_value, Length: 3000, dtype: float64

In [26]:
reg.score(X_test,y_test)

0.6195057678312047

In [27]:
# @title Using Polynomial Regression


In [28]:
from sklearn.preprocessing import PolynomialFeatures

In [29]:
poly=PolynomialFeatures(degree=2)

In [30]:
X_train.shape

(17000, 8)

In [31]:
poly.fit(X_train)

PolynomialFeatures()

In [32]:
X_train=poly.transform(X_train)

In [33]:
X_train.shape

(17000, 45)

In [34]:
reg.fit(X_train,y_train)

LinearRegression()

In [35]:
reg.score(X_train,y_train)

0.7066368555247645

In [36]:
X_test.shape

(3000, 8)

In [37]:
poly.fit(X_test)

PolynomialFeatures()

In [38]:
X_test=poly.transform(X_test)

In [39]:
X_test.shape

(3000, 45)

In [40]:
reg.score(X_test,y_test)

0.6645927987055097

In [41]:
reg.coef_

array([ 8.30575943e-02,  6.33924149e+05,  9.25858755e+05, -7.93261090e+04,
        1.09217692e+03, -4.86728867e+03,  1.36116605e+02, -1.12328493e+03,
       -9.75242137e+05,  4.27397922e+03,  1.14129725e+04, -9.72991445e+02,
        1.42813842e+01, -6.94463653e+01,  1.76214927e+00, -8.15242502e+00,
       -1.26310130e+04,  6.46760812e+03, -1.06552126e+03,  1.55005045e+01,
       -8.49510751e+01,  3.06285668e+00, -2.42342570e+00, -1.33190205e+04,
        1.97160931e+01, -7.00788821e-02,  1.76336148e+00, -1.81775335e+00,
        4.67158334e+00,  7.90170022e+01, -2.49108023e-03,  3.83722617e-02,
       -2.33684643e-03,  3.91870646e-04,  1.03989864e+01, -1.77759354e-01,
        2.10569960e-02,  3.41746881e-02, -5.00677798e+01,  1.47713478e-03,
       -1.74799807e-02, -1.15663829e+01,  2.65450436e-02,  3.44397063e+01,
       -2.59846600e+03])

In [43]:
# @title Lasso Regression


In [52]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split

In [53]:
data_baseball=pd.read_csv('/content/drive/MyDrive/data/baseball.csv')

In [54]:
data_baseball

player    salary     AtBat      Hits     HmRun      Runs  \
0          -Alan Ashby -0.135055 -0.601753 -0.594542 -0.527545 -1.203816   
1         -Alvin Davis -0.123972  0.511566  0.491323  0.728577  0.440675   
2        -Andre Dawson -0.079637  0.626971  0.735088  0.956963  0.401520   
3    -Andres Galarraga -0.985164 -0.561022 -0.461579 -0.184967 -0.616498   
4     -Alfredo Griffin  0.474541  1.292248  1.355583 -0.870124  0.753911   
..                 ...       ...       ...       ...       ...       ...   
258      -Willie McGee  0.363705  0.633760  0.424841 -0.527545  0.401520   
259   -Willie Randolph  0.751630  0.599817  0.624286 -0.755931  0.832220   
260    -Wayne Tolleson -0.334559  0.484412  0.402681 -0.984317  0.244902   
261     -Willie Upshaw  0.940050  1.149689  0.801570 -0.299159  1.184611   
262     -Willie Wilson  1.028718  1.543424  1.377743 -0.299159  0.871375   

          RBI     Walks     Years    CAtBat  ...    CHmRun     CRuns  \
0   -0.521069 -0.097342  1.395233  0.346131  ... -0.002914 -0.121439   
1    0.792549  1.606310 -0.899485 -0.452004  ... -0.075909 -0.414315   
2    1.024364 -0.189431  0.769401  1.299081  ...  1.894952  1.409364   
3   -0.366526 -0.511743 -1.108096 -0.989050  ... -0.696365 -0.945718   
4   -0.018804 -0.281520  0.769401  0.765534  ... -0.611205  0.422041   
..        ...       ...       ...       ...  ...       ...       ...   
258 -0.134711 -0.189431 -0.482264  0.019880  ... -0.453049  0.053682   
259 -0.057440  2.435113  0.978012  1.247913  ... -0.367888  1.617699   
260 -0.327890  0.501239 -0.273653 -0.418766  ... -0.757194 -0.435450   
261  0.328919  1.698399  0.143569  0.236360  ...  0.337728  0.328442   
262 -0.289255 -0.465699  0.769401  0.984201  ... -0.477381  1.249340   

         CRBI    CWalks   LeagueN  DivisionW   PutOuts   Assists    Errors  \
0    0.258473  0.434506  1.056743   0.979299  1.219174 -0.522196  0.212946   
1   -0.199211  0.010353 -0.942706   0.979299  2.105095 -0.253380  0.818404   
2    1.569674  0.354977  1.056743  -1.017256 -0.324044 -0.742763 -0.846605   
3   -0.879551 -0.860675  1.056743  -1.017256  1.837176 -0.542874 -0.695240   
4    0.017261 -0.250955 -0.942706   0.979299 -0.031118  2.083253  2.483412   
..        ...       ...       ...        ...       ...       ...       ...   
258 -0.060050 -0.463031  1.056743  -1.017256  0.122489 -0.756548 -0.846605   
259  0.372894  2.328045 -0.942706  -1.017256  0.079622  1.807544  1.726590   
260 -0.734205 -0.432735 -0.942706   0.979299 -0.906323 -0.039705 -0.241147   
261  0.277028  0.271662 -0.942706  -1.017256  3.655458  0.084364  0.515675   
262  0.082203 -0.042666 -0.942706   0.979299  0.418987 -0.791012 -0.846605   

     NewLeagueN  
0      1.073007  
1     -0.928417  
2      1.073007  
3      1.073007  
4     -0.928417  
..          ...  
258    1.073007  
259   -0.928417  
260   -0.928417  
261   -0.928417  
262   -0.928417  

[263 rows x 21 columns]

In [56]:
X=data_baseball.drop(columns=['player','salary'])
y=data_baseball['salary']

In [61]:
data_baseball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   player      263 non-null    object 
 1   salary      263 non-null    float64
 2   AtBat       263 non-null    float64
 3   Hits        263 non-null    float64
 4   HmRun       263 non-null    float64
 5   Runs        263 non-null    float64
 6   RBI         263 non-null    float64
 7   Walks       263 non-null    float64
 8   Years       263 non-null    float64
 9   CAtBat      263 non-null    float64
 10  CHits       263 non-null    float64
 11  CHmRun      263 non-null    float64
 12  CRuns       263 non-null    float64
 13  CRBI        263 non-null    float64
 14  CWalks      263 non-null    float64
 15  LeagueN     263 non-null    float64
 16  DivisionW   263 non-null    float64
 17  PutOuts     263 non-null    float64
 18  Assists     263 non-null    float64
 19  Errors      263 non-null    f

In [58]:
X

AtBat      Hits     HmRun      Runs       RBI     Walks     Years  \
0   -0.601753 -0.594542 -0.527545 -1.203816 -0.521069 -0.097342  1.395233   
1    0.511566  0.491323  0.728577  0.440675  0.792549  1.606310 -0.899485   
2    0.626971  0.735088  0.956963  0.401520  1.024364 -0.189431  0.769401   
3   -0.561022 -0.461579 -0.184967 -0.616498 -0.366526 -0.511743 -1.108096   
4    1.292248  1.355583 -0.870124  0.753911 -0.018804 -0.281520  0.769401   
..        ...       ...       ...       ...       ...       ...       ...   
258  0.633760  0.424841 -0.527545  0.401520 -0.134711 -0.189431 -0.482264   
259  0.599817  0.624286 -0.755931  0.832220 -0.057440  2.435113  0.978012   
260  0.484412  0.402681 -0.984317  0.244902 -0.327890  0.501239 -0.273653   
261  1.149689  0.801570 -0.299159  1.184611  0.328919  1.698399  0.143569   
262  1.543424  1.377743 -0.299159  0.871375 -0.289255 -0.465699  0.769401   

       CAtBat     CHits    CHmRun     CRuns      CRBI    CWalks   LeagueN  \
0    0.346131  0.174042 -0.002914 -0.121439  0.258473  0.434506  1.056743   
1   -0.452004 -0.409112 -0.075909 -0.414315 -0.199211  0.010353 -0.942706   
2    1.299081  1.315665  1.894952  1.409364  1.569674  0.354977  1.056743   
3   -0.989050 -0.958326 -0.696365 -0.945718 -0.879551 -0.860675  1.056743   
4    0.765534  0.633776 -0.611205  0.422041  0.017261 -0.250955 -0.942706   
..        ...       ...       ...       ...       ...       ...       ...   
258  0.019880  0.129302 -0.453049  0.053682 -0.060050 -0.463031  1.056743   
259  1.247913  1.216930 -0.367888  1.617699  0.372894  2.328045 -0.942706   
260 -0.418766 -0.446138 -0.757194 -0.435450 -0.734205 -0.432735 -0.942706   
261  0.236360  0.207982  0.337728  0.328442  0.277028  0.271662 -0.942706   
262  0.984201  1.133622 -0.477381  1.249340  0.082203 -0.042666 -0.942706   

     DivisionW   PutOuts   Assists    Errors  NewLeagueN  
0     0.979299  1.219174 -0.522196  0.212946    1.073007  
1     0.979299  2.105095 -0.253380  0.818404   -0.928417  
2    -1.017256 -0.324044 -0.742763 -0.846605    1.073007  
3    -1.017256  1.837176 -0.542874 -0.695240    1.073007  
4     0.979299 -0.031118  2.083253  2.483412   -0.928417  
..         ...       ...       ...       ...         ...  
258  -1.017256  0.122489 -0.756548 -0.846605    1.073007  
259  -1.017256  0.079622  1.807544  1.726590   -0.928417  
260   0.979299 -0.906323 -0.039705 -0.241147   -0.928417  
261  -1.017256  3.655458  0.084364  0.515675   -0.928417  
262   0.979299  0.418987 -0.791012 -0.846605   -0.928417  

[263 rows x 19 columns]

In [59]:
y

0     -0.135055
1     -0.123972
2     -0.079637
3     -0.985164
4      0.474541
         ...   
258    0.363705
259    0.751630
260   -0.334559
261    0.940050
262    1.028718
Name: salary, Length: 263, dtype: float64

In [63]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [65]:
X_train.shape


(197, 19)

In [67]:
X_test.shape

(66, 19)

In [79]:
Lasso_reg=Lasso(alpha=0.3)

In [80]:
Lasso_reg.fit(X_train,y_train)

Lasso(alpha=0.3)

In [81]:
Lasso_reg.score(X_train,y_train)

0.35121607242677566

In [82]:
Lasso_reg.score(X_test,y_test)

0.19761552837941843

In [95]:
Lasso_reg.coef_

array([ 0.        ,  0.07067128,  0.        ,  0.        ,  0.01998016,
        0.05000115,  0.        ,  0.        ,  0.        ,  0.        ,
        0.24309776,  0.00737268,  0.        , -0.        , -0.        ,
        0.        ,  0.        ,  0.        , -0.        ])

In [84]:
# @title DRigde Regression


In [87]:
from sklearn.linear_model import Ridge

In [90]:
Ridge_reg=Ridge(alpha=0.3)

In [91]:
Ridge_reg.fit(X_train,y_train)

Ridge(alpha=0.3)

In [92]:
Ridge_reg.score(X_train,y_train)

0.6169550091419604

In [94]:
Ridge_reg.score(X_test,y_test)

0.2773325130451929

In [96]:
Ridge_reg.coef_

array([-0.5295138 ,  0.49337322,  0.00179158, -0.01941938,  0.12110385,
        0.2725519 , -0.14470656, -0.55792477,  0.63972541, -0.02521332,
        0.63557152,  0.14314033, -0.24842815,  0.13575488, -0.08650643,
        0.1870159 ,  0.05716566, -0.01830499, -0.15639752])

In [97]:
# @title ElasticNet


In [98]:
from sklearn.linear_model import ElasticNet

In [99]:
Elastic_reg=ElasticNet(alpha=0.3)

In [100]:
Elastic_reg.fit(X_train,y_train)

ElasticNet(alpha=0.3)

In [102]:
Elastic_reg.score(X_train,y_train)

0.48645510264808245

In [103]:
Elastic_reg.score(X_test,y_test)

0.2496951819827975

In [104]:
Elastic_reg.coef_

array([ 0.        ,  0.08830956,  0.        ,  0.05155656,  0.04121128,
        0.09885829,  0.        ,  0.        ,  0.11142563,  0.        ,
        0.13753786,  0.09600185,  0.        ,  0.        , -0.        ,
        0.05038053,  0.        , -0.        , -0.        ])

In [105]:
Elastic_reg.coef_

array([ 0.        ,  0.08830956,  0.        ,  0.05155656,  0.04121128,
        0.09885829,  0.        ,  0.        ,  0.11142563,  0.        ,
        0.13753786,  0.09600185,  0.        ,  0.        , -0.        ,
        0.05038053,  0.        , -0.        , -0.        ])